"""empty message

Revision ID: 6ad8b6ea56d3
Revises: 
Create Date: 2023-11-16 10:47:48.690476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad8b6ea56d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('team',
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('pokemon_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.name'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('user')
    # ### end Alembic commands ###
